// Re-export the single authenticated Supabase client so that all DB calls
// share the same auth session (otherwise RLS sees an anonymous request).
import { supabase } from '@/integrations/supabase/client';
export { supabase };
export { SUPABASE_URL, SUPABASE_ANON_KEY, SUPABASE_PUBLISHABLE_KEY } from '@/integrations/supabase/client';

// ==================== TYPES (match your DB schema) ====================
// Note: created_date/updated_date are auto-generated by DB triggers
export interface Group {
  id: string;
  owner_id?: string | null;
  service_name: string;
  service_type: string;
  plan_type?: string;
  total_cost: number;
  currency: string;
  max_members: number;
  billing_date: number;
  description: string;
  invite_code: string;
  status: string;
  is_public: boolean;
  admin_email: string;
  stripe_account_id?: string | null;
  cover_image_url?: string | null;
  admin_name?: string | null;
  member_count?: number;
  created_date?: string;
  updated_date?: string;
}

export interface Membership {
  id: string;
  group_id: string;
  user_email: string;
  user_name: string;
  user_avatar_url: string | null;
  role: string;
  payment_status: string;
  joined_date: string;
  created_date?: string;
  updated_date?: string;
  cred_status?: string | null;
  cred_status_at?: string | null;
  cred_issue_note?: string | null;
  removal_requested_at?: string | null;
  removal_effective_at?: string | null;

}

export interface Payment {
  id: string;
  group_id: string;
  membership_id: string;
  user_email: string;
  amount: number;
  platform_fee: number;
  owner_amount: number;
  payment_date: string;
  payment_method: string;
  billing_month: string;
  status: string;
  stripe_payment_intent_id?: string;
  stripe_transfer_id?: string;
  created_date?: string;
}

export interface Notification {
  id: string;
  user_email: string;
  type: string;
  title: string;
  content: string;
  link?: string;
  group_id?: string;
  read: boolean;
  created_date?: string;
}

export interface TrustScore {
  id: string;
  user_email: string;
  score: number;
  phone_verified: boolean;
  kyc_verified: boolean;
  invites_count: number;
  groups_created: number;
  payments_completed: number;
  verified_badges: string[];
  created_date?: string;
  updated_date?: string;
}

// ==================== GROUPS ====================
export const getGroups = async (filters: {
  is_public?: boolean;
  status?: string;
  admin_email?: string;
} = {}): Promise<Group[]> => {
  try {
    // Public browsing → SECURITY DEFINER RPC that exposes only non-sensitive columns.
    if (filters.is_public === true && !filters.admin_email) {
      const { data, error } = await (supabase as any).rpc('get_public_groups');
      if (error) throw error;
      return (data as Group[]) || [];
    }

    // Owner/member browsing → base table (RLS scopes to owner/member).
    let query = supabase.from('groups').select('*');
    if (filters.is_public !== undefined) query = query.eq('is_public', filters.is_public);
    if (filters.status) query = query.eq('status', filters.status);
    // NB: admin_email is column-revoked. Owner is already restricted by RLS,
    // so we simply return what the caller can see and let the caller filter.

    const { data, error } = await query.order('created_date', { ascending: false });
    if (error) throw error;

    let rows = (data as Group[]) || [];
    if (filters.admin_email) {
      const target = filters.admin_email.toLowerCase();
      // admin_email is not selectable; fall back to owner_id match via current session.
      const { data: sess } = await supabase.auth.getSession();
      const uid = sess.session?.user?.id;
      const email = sess.session?.user?.email?.toLowerCase();
      if (email === target && uid) {
        rows = rows.filter(g => g.owner_id === uid);
      } else {
        rows = [];
      }
    }
    return rows;
  } catch (error) {
    console.error('❌ getGroups error:', error);
    return [];
  }
};

export const getGroupById = async (id: string): Promise<Group | null> => {
  try {
    // Try full row first (owner / admin / member with RLS access).
    const full = await supabase.from('groups').select('*').eq('id', id).maybeSingle();
    if (full.data) return full.data as Group;
    // Fallback: safe RPC for non-members of public groups.
    const { data } = await (supabase as any).rpc('get_public_group', { _id: id });
    const row = Array.isArray(data) ? data[0] : data;
    return (row as Group) || null;
  } catch (error) {
    console.error('❌ getGroupById error:', error);
    return null;
  }
};


export const getGroupByInviteCode = async (inviteCode: string): Promise<Group | null> => {
  try {
    const { data, error } = await supabase.rpc('get_group_by_invite_code', {
      _code: inviteCode.toUpperCase(),
    });
    if (error) {
      console.error('❌ Error fetching group by invite code:', error);
      throw error;
    }
    const row = Array.isArray(data) ? data[0] : data;
    return (row as Group) || null;
  } catch (error) {
    console.error('❌ getGroupByInviteCode error:', error);
    return null;
  }
};

export const createGroup = async (groupData: Omit<Group, 'id'>): Promise<Group> => {
  const { data: sessionData, error: sessionError } = await supabase.auth.getSession();
  const session = sessionData.session;

  if (sessionError || !session?.user?.id || !session.user.email) {
    console.error('❌ Missing Supabase auth session while creating group:', sessionError);
    throw new Error('Devi effettuare di nuovo l’accesso prima di creare un gruppo.');
  }

  const authenticatedGroupData = {
    ...groupData,
    owner_id: session.user.id,
    admin_email: session.user.email.toLowerCase(),
  };

  const { data, error } = await supabase
    .from('groups')
    .insert([authenticatedGroupData] as any)
    .select()
    .single();
  
  if (error) {
    console.error('❌ Error creating group:', error);
    throw error;
  }
  
  return data;
};

export const updateGroup = async (id: string, updates: Partial<Group>): Promise<Group> => {
  const { data, error } = await supabase
    .from('groups')
    .update(updates as any)
    .eq('id', id)
    .select()
    .single();
  
  if (error) {
    console.error('❌ Error updating group:', error);
    throw error;
  }
  
  return data;
};

export const deleteGroup = async (id: string): Promise<void> => {
  const { error } = await supabase
    .from('groups')
    .delete()
    .eq('id', id);
  
  if (error) {
    console.error('❌ Error deleting group:', error);
    throw error;
  }
};

// ==================== MEMBERSHIPS ====================
export const getMemberships = async (filters: {
  group_id?: string;
  user_email?: string;
} = {}): Promise<Membership[]> => {
  try {
    // Listing members of a specific group → SECURITY DEFINER RPC that
    // strips Stripe IDs and other sensitive co-member fields.
    if (filters.group_id && !filters.user_email) {
      const { data, error } = await (supabase as any).rpc('get_group_members', {
        _group_id: filters.group_id,
      });
      if (error) throw error;
      return (data as Membership[]) || [];
    }

    // NB: `select('*')` fails with "permission denied" because Stripe columns are
    // column-revoked for `authenticated`. Select only the readable columns.
    const MEMBERSHIP_COLUMNS = [
      'id', 'group_id', 'user_email', 'user_name', 'user_avatar_url', 'role',
      'payment_status', 'cost_per_month', 'joined_date', 'created_date',
      'current_period_end', 'dunning_attempts', 'slot_type', 'duration_hours',
      'access_expires_at', 'auto_renew', 'cred_status', 'cred_status_at',
      'cred_issue_note', 'removal_requested_at', 'removal_effective_at',
      'removal_requested_by',
    ].join(', ');

    let query = supabase.from('memberships').select(MEMBERSHIP_COLUMNS);
    if (filters.group_id) query = query.eq('group_id', filters.group_id);
    if (filters.user_email) query = query.eq('user_email', filters.user_email);

    const { data, error } = await query.order('joined_date', { ascending: false });
    if (error) throw error;
    return (data || []) as unknown as Membership[];
  } catch (error) {
    console.error('❌ getMemberships error:', error);
    return [];
  }
};

export const getMembershipsByGroupId = async (groupId: string): Promise<Membership[]> => {
  return getMemberships({ group_id: groupId });
};

export const getUserMemberships = async (userEmail: string): Promise<Membership[]> => {
  return getMemberships({ user_email: userEmail });
};


export const createMembership = async (membershipData: Omit<Membership, 'id'>): Promise<Membership> => {
  const { data, error } = await supabase
    .from('memberships')
    .insert([membershipData] as any)
    .select()
    .single();
  
  if (error) {
    console.error('❌ Error creating membership:', error);
    throw error;
  }
  
  return data;
};

export const updateMembership = async (id: string, updates: Partial<Membership>): Promise<Membership> => {
  const { data, error } = await supabase
    .from('memberships')
    .update(updates as any)
    .eq('id', id)
    .select()
    .single();
  
  if (error) {
    console.error('❌ Error updating membership:', error);
    throw error;
  }
  
  return data;
};

export const deleteMembership = async (id: string): Promise<void> => {
  const { error } = await supabase
    .from('memberships')
    .delete()
    .eq('id', id);
  
  if (error) {
    console.error('❌ Error deleting membership:', error);
    throw error;
  }
};

export const deleteMembershipByGroupAndUser = async (groupId: string, userEmail: string): Promise<void> => {
  const { error } = await supabase
    .from('memberships')
    .delete()
    .eq('group_id', groupId)
    .eq('user_email', userEmail);
  
  if (error) {
    console.error('❌ Error deleting membership:', error);
    throw error;
  }
};

// ==================== PAYMENTS ====================
export const getPayments = async (filters: {
  user_email?: string;
  group_id?: string;
} = {}): Promise<Payment[]> => {
  try {
    let query = supabase.from('payments').select('*');
    
    if (filters.user_email) {
      query = query.eq('user_email', filters.user_email);
    }
    if (filters.group_id) {
      query = query.eq('group_id', filters.group_id);
    }
    
    const { data, error } = await query.order('payment_date', { ascending: false });
    
    if (error) {
      console.error('❌ Error fetching payments:', error);
      throw error;
    }
    
    return data || [];
  } catch (error) {
    console.error('❌ getPayments error:', error);
    return [];
  }
};

export const createPayment = async (paymentData: Omit<Payment, 'id'>): Promise<Payment> => {
  const { data, error } = await supabase
    .from('payments')
    .insert([paymentData] as any)
    .select()
    .single();
  
  if (error) {
    console.error('❌ Error creating payment:', error);
    throw error;
  }
  
  return data;
};

// ==================== NOTIFICATIONS ====================
export const getNotifications = async (userEmail: string): Promise<Notification[]> => {
  try {
    const { data: sessionData } = await supabase.auth.getSession();
    if (!sessionData.session) return [];

    const { data, error } = await supabase
      .from('notifications')
      .select('*')
      .eq('user_email', userEmail)
      .order('created_date', { ascending: false })
      .limit(50);
    
    if (error) {
      if ((error as any).code === '401' || (error as any).message?.includes('JWT')) return [];
      console.error('❌ Error fetching notifications:', error);
      throw error;
    }
    
    return data || [];
  } catch (error) {
    console.error('❌ getNotifications error:', error);
    return [];
  }
};

export const createNotification = async (notificationData: Omit<Notification, 'id' | 'read'>): Promise<Notification> => {
  const { data, error } = await supabase
    .from('notifications')
    .insert([{ ...notificationData, read: false }])
    .select()
    .single();
  
  if (error) {
    console.error('❌ Error creating notification:', error);
    throw error;
  }
  
  return data;
};

export const markNotificationAsRead = async (id: string): Promise<void> => {
  const { error } = await supabase
    .from('notifications')
    .update({ read: true })
    .eq('id', id);
  
  if (error) {
    console.error('❌ Error marking notification as read:', error);
    throw error;
  }
};

export const updateNotification = async (id: string, updates: Partial<Notification>): Promise<Notification | null> => {
  const { data, error } = await supabase
    .from('notifications')
    .update(updates as any)
    .eq('id', id)
    .select()
    .maybeSingle();
  
  if (error) {
    console.error('❌ Error updating notification:', error);
    throw error;
  }
  
  return data;
};

export const markAllNotificationsAsRead = async (userEmail: string): Promise<void> => {
  const { error } = await supabase
    .from('notifications')
    .update({ read: true })
    .eq('user_email', userEmail)
    .eq('read', false);
  
  if (error) {
    console.error('❌ Error marking all notifications as read:', error);
    throw error;
  }
};

// ==================== TRUST SCORES ====================
export const getTrustScore = async (userEmail: string): Promise<TrustScore | null> => {
  try {
    const { data, error } = await supabase
      .from('trust_scores')
      .select('*')
      .eq('user_email', userEmail)
      .maybeSingle();
    
    if (error) {
      console.error('❌ Error fetching trust score:', error);
      return null;
    }
    
    return data as any;
  } catch (error) {
    console.error('❌ getTrustScore error:', error);
    return null;
  }
};

export const createOrUpdateTrustScore = async (
  userEmail: string, 
  updates: Partial<Omit<TrustScore, 'id' | 'user_email'>>
): Promise<TrustScore> => {
  const { data, error } = await supabase
    .from('trust_scores')
    .upsert([{ 
      user_email: userEmail, 
      ...updates,
      last_updated: new Date().toISOString()
    }] as any, { onConflict: 'user_email' })
    .select()
    .single() as any;
  
  if (error) {
    console.error('❌ Error upserting trust score:', error);
    throw error;
  }
  
  return data;
};

// ==================== REAL-TIME SUBSCRIPTIONS ====================
export const subscribeToGroupChanges = (
  groupId: string, 
  callback: (payload: any) => void
): (() => void) => {
  const channel = supabase
    .channel(`group-${groupId}`)
    .on(
      'postgres_changes',
      { 
        event: '*', 
        schema: 'public', 
        table: 'groups', 
        filter: `id=eq.${groupId}` 
      },
      (payload) => callback(payload)
    )
    .subscribe();
  
  return () => {
    supabase.removeChannel(channel);
  };
};

export const subscribeToMembershipChanges = (
  groupId: string, 
  callback: (payload: any) => void
): (() => void) => {
  const channel = supabase
    .channel(`memberships-${groupId}`)
    .on(
      'postgres_changes',
      { 
        event: '*', 
        schema: 'public', 
        table: 'memberships', 
        filter: `group_id=eq.${groupId}` 
      },
      (payload) => callback(payload)
    )
    .subscribe();
  
  return () => {
    supabase.removeChannel(channel);
  };
};

// ==================== HELPER FUNCTIONS ====================
export const generateInviteCode = (): string => {
  const chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";
  let code = "";
  for (let i = 0; i < 6; i++) {
    code += chars.charAt(Math.floor(Math.random() * chars.length));
  }
  return code;
};

export const checkIfUserIsMember = async (groupId: string, userEmail: string): Promise<boolean> => {
  const memberships = await getMemberships({ group_id: groupId, user_email: userEmail });
  return memberships.length > 0;
};

export const getGroupMemberCount = async (groupId: string): Promise<number> => {
  const memberships = await getMemberships({ group_id: groupId });
  return memberships.length;
};
