import { useState } from "react";
import { Link } from "react-router-dom";
import { ArrowRight, ArrowUpRight, Check, Heart, LockKeyhole, Play, ShieldCheck, Sparkles, UsersRound, Wallet } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from "@/components/ui/card";
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";
import { Badge } from "@/components/ui/badge";
import { Slider } from "@/components/ui/slider";
import { Field, FieldLabel } from "@/components/ui/field";
import { Reveal, RevealGroup, RevealItem } from "@/components/motion/Reveal";
import ServiceLogo from "@/components/ServiceLogo";
import { euro } from "@/components/dashboard/SubscriptionTile";

const services = [
  { name: "Netflix", label: "Le storie che ami.", price: 17.99, people: 4 },
  { name: "Spotify", label: "La colonna sonora di tutto.", price: 21.99, people: 6 },
  { name: "Disney+", label: "Un mondo da scoprire.", price: 13.99, people: 4 },
  { name: "Microsoft 365", label: "Spazio alle tue idee.", price: 9.99, people: 6 },
];
const benefits = [
  { icon: UsersRound, title: "Trova il tuo gruppo.", body: "Esplora le tue passioni e trova persone con cui condividere un abbonamento. Oppure crea il tuo gruppo." },
  { icon: Wallet, title: "Ognuno fa la sua parte.", body: "Quote, rinnovi e pagamenti in un unico spazio. Sai sempre quanto spendi, senza rincorrere nessuno." },
  { icon: Heart, title: "Goditi tutto il resto.", body: "Le tue serie, la tua musica, le tue idee. Lo stesso abbonamento che ami, un mese un po’ più leggero." },
];
const questions = [
  { question: "Che cos’è DivideIt?", answer: "DivideIt è uno spazio per organizzare gruppi e dividere le spese di abbonamenti digitali. Non rivende abbonamenti: aiuta i membri a gestire le proprie quote e a comunicare, nel rispetto delle condizioni di ciascun servizio." },
  { question: "Posso condividere qualsiasi abbonamento?", answer: "Ogni servizio ha le proprie regole. Puoi condividere soltanto i piani che lo consentono e con persone che rispettano i requisiti previsti, compresi eventuali vincoli di nucleo familiare o residenza." },
  { question: "Come vengono gestiti i pagamenti?", answer: "Puoi tenere sotto controllo quote e movimenti dal portafoglio. Nell’app operativa i pagamenti sono gestiti dal sistema già presente. Nella modalità anteprima nessuna operazione viene inviata e gli importi sono puramente illustrativi." },
  { question: "Posso creare un gruppo con i miei amici?", answer: "Certo. Scegli il servizio, definisci la quota e invita le persone con cui puoi condividerlo. Avrete uno spazio comune per messaggi e scadenze. L’anteprima permette di esplorare anche questo percorso senza creare dati reali." },
];

export default function MarketingSections({ onStart }: { onStart: () => void }) {
  const [people, setPeople] = useState(4);
  return (
    <>
      <section className="service-strip" aria-label="Le tue passioni in un solo posto"><div className="marketing-container"><p>Le tue passioni. Finalmente, tutte insieme.</p><div className="service-wordmarks">{["Netflix", "Spotify", "Disney+", "YouTube Premium", "Microsoft 365"].map((service) => <span key={service}><ServiceLogo name={service} size={30} decorative /><span className="font-display">{service}</span></span>)}</div></div></section>
      <section id="come-funziona" className="marketing-section"><div className="marketing-container"><Reveal><span className="marketing-eyebrow">SEMPLICE, COME DOVREBBE ESSERE.</span><h2 className="marketing-title">Dividere le spese.<br /><span className="text-muted-foreground">Non complicarsi la vita.</span></h2></Reveal><RevealGroup className="benefit-grid">{benefits.map(({ icon: Icon, title, body }) => <RevealItem key={title}><div className="benefit-icon"><Icon className="size-6" strokeWidth={1.7} /></div><h3 className="font-display text-xl font-bold">{title}</h3><p className="pt-3 text-base leading-relaxed text-muted-foreground">{body}</p></RevealItem>)}</RevealGroup></div></section>
      <section id="servizi" className="marketing-section marketing-services"><div className="marketing-container"><Reveal><div className="section-heading"><div><span className="marketing-eyebrow">FAI SPAZIO A QUELLO CHE AMI.</span><h2 className="marketing-title">Piccole quote.<br />Grandi passioni.</h2></div><Button variant="outline" asChild><Link to="/BrowseGroups">Esplora tutti i gruppi<ArrowUpRight data-icon="inline-end" /></Link></Button></div></Reveal><RevealGroup className="marketing-service-grid">{services.map((service) => <RevealItem key={service.name}><Card className="marketing-service-card"><CardHeader><span className="service-tile"><ServiceLogo name={service.name} size={34} decorative /></span><div className="pt-5"><CardTitle>{service.name}</CardTitle><CardDescription className="pt-1.5">{service.label}</CardDescription></div></CardHeader><CardContent><p className="text-sm text-muted-foreground">Esempio di quota condivisa</p><p className="pt-2 font-display text-3xl font-bold">{euro(service.price / service.people)}<span className="text-sm font-normal text-muted-foreground"> / mese</span></p></CardContent><CardFooter><Button variant="outline" asChild className="w-full"><Link to={`/BrowseGroups?q=${encodeURIComponent(service.name)}`}>Trova il tuo gruppo<ArrowUpRight data-icon="inline-end" /></Link></Button></CardFooter></Card></RevealItem>)}</RevealGroup><p className="pt-5 text-sm leading-relaxed text-muted-foreground">Importi illustrativi, non offerte di vendita. Disponibilità, prezzi e idoneità alla condivisione dipendono dal piano e dalle condizioni del singolo servizio. <Link to="/legal/regole-condivisione" className="text-primary underline underline-offset-4">Consulta le regole di condivisione</Link>.</p></div></section>
      <section id="risparmio" className="marketing-section"><div className="marketing-container"><Reveal><div className="savings-feature"><div><span className="marketing-eyebrow">FALLO TU, IL CONTO.</span><h2 className="marketing-title">La stessa passione.<br />Una spesa più piccola.</h2><p className="max-w-md pt-3 text-base leading-relaxed text-muted-foreground">Prendiamo un abbonamento da 20 € al mese. Guarda cosa succede quando ognuno mette la sua parte.</p><Field className="pt-8"><FieldLabel htmlFor="sharing-people">Quante persone condividono? <strong>{people}</strong></FieldLabel><div className="pt-4"><Slider id="sharing-people" min={2} max={6} step={1} value={[people]} onValueChange={([value]) => setPeople(value)} aria-label="Numero di persone con cui dividere la spesa" /></div><div className="flex justify-between pt-2 text-sm text-muted-foreground"><span>2 persone</span><span>6 persone</span></div></Field></div><div className="savings-receipt"><div className="flex items-center justify-between"><span className="font-display font-bold">La tua parte.</span><Badge variant="secondary"><UsersRound className="mr-1 size-3.5" />{people} persone</Badge></div><p className="savings-amount font-display">{euro(20 / people)}</p><p className="text-sm text-muted-foreground">al mese, invece di 20,00 €</p><div className="savings-receipt-total"><span>Il tuo risparmio in un anno</span><strong>{euro((20 - 20 / people) * 12)}</strong></div><Button className="w-full" size="lg" onClick={onStart}>Mi piace, iniziamo<ArrowRight data-icon="inline-end" /></Button><p className="pt-3 text-center text-sm text-muted-foreground">Esempio di calcolo, non include eventuali commissioni.</p></div></div></Reveal></div></section>
      <section id="sicurezza" className="marketing-section marketing-security"><div className="marketing-container"><Reveal><div className="security-layout"><span className="security-symbol"><ShieldCheck strokeWidth={1.2} /></span><div><span className="marketing-eyebrow">LA TRANQUILLITÀ NON SI DIVIDE.</span><h2 className="marketing-title">Condividi di più.<br />Preoccupati di meno.</h2><p className="max-w-xl pt-4 text-base leading-relaxed text-muted-foreground">Un buon gruppo si basa sulla fiducia. Per questo quote, persone e conversazioni hanno il proprio posto, sempre a portata di mano.</p><div className="security-checks"><span><Check />Movimenti chiari</span><span><Check />Profili riconoscibili</span><span><Check />Controllo sulle tue spese</span></div></div></div></Reveal></div></section>
      <section className="marketing-section"><div className="marketing-container"><div className="faq-layout"><Reveal><span className="marketing-eyebrow">FACCIAMO CHIAREZZA.</span><h2 className="marketing-title">Una domanda?<br />Ci siamo.</h2><p className="pt-4 text-base text-muted-foreground">Le risposte, senza giri di parole.</p><div className="pt-6"><Button variant="outline" asChild><Link to="/Support">Parliamone<ArrowUpRight data-icon="inline-end" /></Link></Button></div></Reveal><Accordion type="single" collapsible>{questions.map(({ question, answer }, index) => <AccordionItem value={`faq-${index}`} key={question}><AccordionTrigger className="text-left text-base font-semibold">{question}</AccordionTrigger><AccordionContent className="text-base leading-relaxed text-muted-foreground">{answer}</AccordionContent></AccordionItem>)}</Accordion></div></div></section>
      <section className="marketing-final"><div className="marketing-container"><Reveal><div className="final-layout"><div><h2 className="font-display text-4xl font-semibold leading-tight tracking-tight md:text-5xl">Tutto quello che ami.<br />Con le persone giuste.</h2><p className="pt-4 text-base opacity-80">Il tuo prossimo gruppo è solo a un clic di distanza.</p></div><Button variant="inverse" size="lg" onClick={onStart}>Trova il tuo gruppo<ArrowUpRight data-icon="inline-end" /></Button></div></Reveal></div></section>
    </>
  );
}
